### PR TITLE
Tititopemike

### PR DESCRIPTION
**Pull request by LyonMike01**
Worked on the ajv schema, refactored the create role and also implemented the verify role route.
Also created api using jetbrains spotlight.

### CODE REVIEW

**Comment by LyonMike01** [comment]
Worked on the ajv schema, refactored the create role and also implemented the verify role route.
Also created api using jetbrains spotlight.

**Comment by solomonmarvel97** [comment]
resolve the conflicts first

**Comment by LyonMike01** [comment]
Ressolved conflicts Worked on the ajv schema, refactored the create role and also implemented the verify role route.

**Review by solomonmarvel97 — APPROVED** [review]
Good

**Pull request merged**
